server:
  port: 8001



spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于0 到 1之间，1表示全部采样
      probability: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddemo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmj.springcloud.entities # 所有Entity别名类所在包


eureka:
  client:
    # 表示是否将自己注册进EurekaServer默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须设置微true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径可以显示IP地址