server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: admin

feign:
  hystrix:
    enabled: false


#seata分布式事务配置，此为精简后的配置，大家可根据实际场景适当选择添加修改等
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  #  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace: seata120
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: seata120
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"


logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
